SRCS    := main.c bst.c  bst_tk.c  ssalloc.c libssmem/src/ssmem.c
TARGET  := BSTTK
TREE	:= -DBSTTK
EXTRAC := -Ilibssmem/include -DTAS -DDEFAULT -DGC=1 -DINITIALIZE_FROM_ONE=1 -I../libatomic_ops/src

include  ../common/common.mk
